- name: Declare variable at Play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
        
        
  #### vcariable at task level
- name: Declare variable at Task level
  hosts: all
  connection: local
  
  tasks:
   - name: Declare and Access a variable
     ansible.builtin.debug:
        msg: URL == {{URL}}
     vars:
       URL: task.example.com  
       
### Access variable from file      
- name: Declare variable from file
  hosts: all
  connection: local
  vars_files: 
      - var.yml
  
  tasks:
   - name: Access a variable
     ansible.builtin.debug:
        msg: URL == {{URL}}
 
##### variable from inventory file
- name: Declare variable from inventory file
  hosts: all
  connection: local
  tasks:
    - name: Access variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
 
 
                
         